/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'HP' at '18-12-19 下午2:30' with Gradle 2.14.1
 *
 * @author HP, @date 18-12-19 下午2:30
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
